originalImage=imread('uw1.jpeg');        %Histogram Equalisation
imshow(originalImage);
motblurr=fspecial('motion',15,13);
blurred=imfilter(originalImage,motblurr,'conv','circular');
imshow(blurred);
imwrite(blurred,'C:\Users\Pritesh J Shah\Downloads\dipminiproject\uw1AHE_blurred.jpeg');
originalImage=blurred;
ycbcroriginal=rgb2ycbcr(originalImage);
figure;imshow(ycbcroriginal);
imwrite(ycbcroriginal,'C:\Users\Pritesh J Shah\Downloads\dipminiproject\uw1AHE_ycbcr.jpeg');
ychannel=ycbcroriginal(:,:,1);
figure;imshow(ychannel);
imwrite(ychannel,'C:\Users\Pritesh J Shah\Downloads\dipminiproject\uw1AHE_ycbcr_ychannel.jpeg');
ychannelafterhisteq=adapthisteq(ychannel);
figure;imshow(ychannelafterhisteq);
imwrite(ychannelafterhisteq,'C:\Users\Pritesh J Shah\Downloads\dipminiproject\uw1AHE_ycbcr_ychannelafterHE.jpeg');
ycbcroriginal(:,:,1)=ychannelafterhisteq;
ycbcrafterhisteq=ycbcroriginal;
figure;imshow(ycbcrafterhisteq);
imwrite(ycbcrafterhisteq,'C:\Users\Pritesh J Shah\Downloads\dipminiproject\uw1AHE_ycbcr_afterHE.jpeg');
rgbafterhisteq=ycbcr2rgb(ycbcrafterhisteq);
figure;imshow(rgbafterhisteq);
r=rgbafterhisteq(:,:,1);
g=rgbafterhisteq(:,:,2);
b=rgbafterhisteq(:,:,3);
rfiltered=imgaussfilt(r,2);
bfiltered=imgaussfilt(b,2);
gfiltered=imgaussfilt(g,2);
rgbafterhisteq(:,:,1)=rfiltered;
rgbafterhisteq(:,:,2)=gfiltered;
rgbafterhisteq(:,:,3)=bfiltered;
rgbafterfiltering=rgbafterhisteq;
figure;imshow(rgbafterfiltering);
figure;imshow(imsharpen(rgbafterfiltering));
imwrite(rgbafterfiltering,'C:\Users\Pritesh J Shah\Downloads\dipminiproject\uw1AHE_final.jpeg');